"""Initial migration

Revision ID: 115ce70b1e0e
Revises: 
Create Date: 2025-11-20 19:21:14.936855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '115ce70b1e0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.create_table('ga_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=255), nullable=False),
    sa.Column('property_id', sa.String(length=255), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ga_connections_property_id'), 'ga_connections', ['property_id'], unique=False)
    op.create_index(op.f('ix_ga_connections_workspace_id'), 'ga_connections', ['workspace_id'], unique=False)
    op.create_table('gpt_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpt_tokens_access_token_hash'), 'gpt_tokens', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_gpt_tokens_expires_at'), 'gpt_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_gpt_tokens_refresh_token'), 'gpt_tokens', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_gpt_tokens_revoked'), 'gpt_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_gpt_tokens_workspace_id'), 'gpt_tokens', ['workspace_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('gpt_token_id', sa.UUID(), nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gpt_token_id'], ['gpt_tokens.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_created_at'), 'query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_gpt_token_id'), 'query_logs', ['gpt_token_id'], unique=False)
    op.create_index(op.f('ix_query_logs_workspace_id'), 'query_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_workspace_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_gpt_token_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_created_at'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_gpt_tokens_workspace_id'), table_name='gpt_tokens')
    op.drop_index(op.f('ix_gpt_tokens_revoked'), table_name='gpt_tokens')
    op.drop_index(op.f('ix_gpt_tokens_refresh_token'), table_name='gpt_tokens')
    op.drop_index(op.f('ix_gpt_tokens_expires_at'), table_name='gpt_tokens')
    op.drop_index(op.f('ix_gpt_tokens_access_token_hash'), table_name='gpt_tokens')
    op.drop_table('gpt_tokens')
    op.drop_index(op.f('ix_ga_connections_workspace_id'), table_name='ga_connections')
    op.drop_index(op.f('ix_ga_connections_property_id'), table_name='ga_connections')
    op.drop_table('ga_connections')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
