"""Add google_id and is_google_user to users table

Revision ID: aba5f5d04d4a
Revises: 115ce70b1e0e
Create Date: 2025-11-20 20:29:37.544230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba5f5d04d4a'
down_revision: Union[str, None] = '115ce70b1e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    # Add is_google_user with default False first
    op.add_column('users', sa.Column('is_google_user', sa.Boolean(), nullable=True, server_default='false'))
    # Now make it NOT NULL (after setting default for existing rows)
    op.alter_column('users', 'is_google_user',
               existing_type=sa.Boolean(),
               nullable=False,
               server_default=None)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_google_user')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
